services:
  postgres_db:
    image: postgres
    hostname: pv178_db
    container_name: pv178_db
    restart: always
    environment:
      POSTGRES_DB: pv178
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: project
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true  # Keeps the container running for debugging
    depends_on:
      postgres_db:
        condition: service_healthy
